[updpkg] antergos-kde-setup
Former-commit-id: 776c3d5900828f905e150c7b1dd3b03d2f9fe509

diff --git a/antergos-kde-setup/antergos-kde-setup.install b/antergos-kde-setup/antergos-kde-setup.install
--- a/antergos-kde-setup/antergos-kde-setup.install
+++ b/antergos-kde-setup/antergos-kde-setup.install
@@ -1,10 +1,16 @@
 post_install() {
 	if [[ "${SUDO_USER}" != '' ]]; then
-		_USER="${SUDO_USER}"
+		_ANT_USER="${SUDO_USER}"
+	elif [[ "${USERNAME}" != '' ]]; then
+		_ANT_USER="${USERNAME}"
+	elif [[ "${HOME}" != '' ]]; then
+		_ANT_USER="${HOME#/home/}"
 	else
-		_USER="${USER}"
+		echo "Error: Unable to determine current user."
+		exit 1
 	fi
-	antergos-kde-setup "${_USER}" 'no-overwrite'
+	
+	/usr/bin/antergos-kde-setup "${_ANT_USER}" "no-overwrite"
 }
 
 post_upgrade() {
